config/routes.rb
Restaurant::Application.routes.draw do
  
  match '/index.asp', :to => redirect('/links.html')
  
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users
  
  namespace :admin do
    root :to => redirect {|p, r| "#{r.script_name}/admin/categories" }
    resources :categories do
      scope "/:sort" do
        put 'sort', :on => :member
      end
      resources :items
    end
    
    resources :messages do
      get 'carousel', :on => :member
    end
    
    resources :photos
    resources :cdrs
    resources :orders do
      get 'complete',  :on => :collection
      put 'onlined',   :on => :member
      put 'completed', :on => :member
    end
    
    resources :varieties do
      scope "/:sort" do
        put 'sort', :on => :member
      end
      resources :tags do
        scope "/:sort" do
          put 'sort', :on => :member
        end
      end
    end
  end
  
  resources :categories do
    get  'menu',  :on => :member
    post 'check', :on => :member
    get 'ok',    :on => :member
    post 'add', :on => :member
    get 'add_check', :on => :member
    get 'edit_check', :on => :member
    get 'cancel_check', :on => :member
    get 'list', :on => :member
  end
  
  
  root :to => redirect {|p, r| "#{r.script_name}/categories" }
  
end

app/controllers/admin/tags_controller.rb
#encoding: utf-8
class Admin::TagsController < Admin::BaseController
  before_filter :find_parent
  
  def index
    @search = @parent.children.rank(:row_order).search(params[:search])
    @tags = @search.page(params[:page])
  end
  
  def new
    @tag = @parent.children.new
  end

  def create
    @tag = @parent.children.new(params[:variety])
    
    if @tag.save
      flash[:notice] = "菜单创建成功"
      redirect_to admin_variety_tags_path(@parent)
    else
      render :new
    end
  end
  
  def edit
    @tag = @parent.children.find(params[:id])
  end

  def update
    @tag = @parent.children.find(params[:id])
    if @tag.update_attributes(params[:variety])
      flash[:notice] = "菜单修改成功"
      redirect_to admin_variety_tags_path(@parent)
    else
      render :edit
    end
  end
  
  def destroy
    @tag = Variety.find(params[:id])
    @tag.destroy
    flash[:notice] = "菜单删除成功"
    redirect_to admin_variety_tags_path(@parent)
  end

  def find_parent
    @parent = Variety.find(params[:variety_id]) if params[:variety_id]
  end
  
  def sort
    tags = Variety.rank(:row_order)
    tag = @parent.children.find(params[:id])
    
    index = @parent.children.rank(:row_order).index(tag)
    index = (params[:sort] == 'up') ? (index - 1 < 0 ? 0 : index - 1) : (index + 1 > (@parent.children.size - 1) ? @parent.children.size - 1 : index + 1)
    index = tags.index(@parent.children.rank(:row_order)[index])

    tag.update_attribute :row_order_position, index

    @search = @parent.children.rank(:row_order).search(params[:search])
    @tags = @search.page(params[:page])
  end
end

app/views/admin/tags/_form.html.erb
<%= f.input :en_name %>
<%= f.input :se_name %>
<%= f.input :code %>

<div class="form-actions">
	<%= f.button :submit, class: "btn btn-primary" %>
	
	<%= link_to "返回", admin_variety_tags_path(@parent), :class => "btn btn-primary" %>
</div>

app/views/admin/tags/_list.html.erb
<table id="table" class="table table-bordered">
	<tr>
		<th>英文名</th>
		<th>瑞典名</th>
		<th>操作</th>
	</tr>

<% @tags.each do |tag| %>
	<tr>
		<td><%= tag.en_name %></td>
		<td><%= tag.se_name %></td>
		<td>
			<%= link_to '编辑', edit_admin_variety_tag_path(@parent, tag), class: "btn" %> |
			<%= link_to '删除', admin_variety_tag_path(@parent, tag), confirm: '确定删除?', method: :delete, class: "btn" %>
			
			<div class="btn-group">
				<%= link_to '<i class="icon-chevron-up"></i>'.html_safe, sort_admin_variety_tag_path(@parent, 'up', tag), :remote => true, :method => :put, :class => "btn", :title => "上移" %>
				<%= link_to '<i class="icon-chevron-down"></i>'.html_safe, sort_admin_variety_tag_path(@parent, 'down', tag), :remote => true, :method => :put, :class => "btn", :title => "下移" %>
			</div>
		</td>
	</tr>
<% end %>
</table>

app/views/admin/tags/edit.html.erb
<h2 class="page-header">修改菜单</h2>

<%= simple_form_for(@tag, :url => admin_variety_tag_path(@parent, @tag) ) do |f| %>
	<%= render :partial => "form", :locals => { :f => f } %>
<% end %>

app/views/admin/tags/index.html.erb
<%= content_for :head do %>
	<style type="text/css">
		.btn-group {
			float: right;
		}
	</style>
<% end %>
<h2 class="page-header">菜单列表</h2>

<%= render :partial => "list" %>

<br />

<%= link_to '新分类', new_admin_variety_tag_path(@parent), class: "btn btn-primary" %>
<%= link_to '返回上级', admin_varieties_path, class: "btn" %>

app/views/admin/tags/new.html.erb
<h2 class="page-header">新增菜单</h2>
<%= simple_form_for(@tag, :url => admin_variety_tags_path(@parent) ) do |f| %>
<%= render :partial => "form", :locals => { :f => f } %>
<% end %>

app/views/admin/tags/sort.js.erb
$('#table').html(<%=raw render(:partial => 'list').to_json %>);