config/routes.rb
Restaurant::Application.routes.draw do
  
  match '/index.asp', :to => redirect('/links.html')
  
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users
  
  namespace :admin do
    root :to => redirect {|p, r| "#{r.script_name}/admin/categories" }
    resources :categories do
      scope "/:sort" do
        put 'sort', :on => :member
      end
      resources :items
    end
    
    resources :messages do
      get 'carousel', :on => :member
    end
    
    resources :photos
    resources :cdrs
    resources :orders do
      get 'complete',  :on => :collection
      put 'onlined',   :on => :member
      put 'completed', :on => :member
    end
    
    resources :varieties do
      scope "/:sort" do
        put 'sort', :on => :member
      end
      resources :tags do
        scope "/:sort" do
          put 'sort', :on => :member
        end
      end
    end
  end
  
  resources :categories do
    get  'menu',  :on => :member
    post 'check', :on => :member
    get 'ok',    :on => :member
    post 'add', :on => :member
    get 'add_check', :on => :member
    get 'edit_check', :on => :member
    get 'cancel_check', :on => :member
    get 'list', :on => :member
  end
  
  
  root :to => redirect {|p, r| "#{r.script_name}/categories" }
  
end

app/models/variety.rb
class Variety < ActiveRecord::Base
  has_and_belongs_to_many :checks
  has_ancestry
  include RankedModel
  ranks :row_order
  attr_accessible :en_name, :se_name, :code, :row_order
end

app/controllers/admin/varieties_controller.rb
#encoding: utf-8
class Admin::VarietiesController < Admin::BaseController
  def index
    @varieties = Variety.roots.rank(:row_order).page(params[:page]).per(20)
  end
  
  def new
    @variety = Variety.new
  end

  def create
    @variety = Variety.new(params[:variety])
    
    if @variety.save
      flash[:notice] = "模块创建成功"
      redirect_to admin_varieties_path
    else
      render :new
    end
  end
  
  def edit
    @variety = Variety.find(params[:id])
  end

  def update
    @variety = Variety.find(params[:id])
    if @variety.update_attributes(params[:variety])
      flash[:notice] = "模块修改成功"
      redirect_to admin_varieties_path
    else
      render :edit
    end
  end
  
  def destroy
    @variety = Variety.find(params[:id])
    @variety.destroy
    flash[:notice] = "模块删除成功"
    redirect_to admin_varieties_path
  end
  
  def sort
    varieties = Variety.roots.rank(:row_order)
    variety = Variety.find(params[:id])
    
    index = varieties.index(variety)
    index = (params[:sort] == 'up') ? ((index - 1) < 0 ? 0 : index - 1) : ((index + 1 > varieties.size - 1) ? varieties.size - 1 : index + 1)
    index = Variety.rank(:row_order).index(varieties[index])
    variety.update_attribute :row_order_position, index
    
    @varieties = Variety.roots.rank(:row_order).page(params[:page]).per(20)
  end
end

app/views/admin/varieties/_form.html.erb
<%= f.input :en_name %>
<%= f.input :se_name %>
<%= f.input :code %>
<div class="form-actions">
	<%= f.button :submit, class: "btn btn-primary" %>
	<%= link_to "返回", admin_categories_path %>
</div>

app/views/admin/varieties/_list.html.erb
<table id="table" class="table table-striped table-bordered table-condensed">
    <thead>
        <tr>
            <th>英文名</th>
            <th>瑞典名</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
    <% @varieties.each do |variety| %>
        <tr>
            <td><%= variety.en_name %></td>
            <td><%= variety.se_name %></td>
            <td>
                <%= link_to '编辑', edit_admin_variety_path(variety) %>|
                <%= link_to '子选项', admin_variety_tags_path(variety), class: "btn" %>|
                <%= link_to '删除', admin_variety_path(variety), confirm: 'Are you sure?', method: :delete,class: "btn" %>
                <div class="btn-group">
                    <%= link_to '<i class="icon-chevron-up"></i>'.html_safe, sort_admin_variety_path('up', variety), :remote => true, :method => :put, :class => "btn", :title => "上移" %>
                    <%= link_to '<i class="icon-chevron-down"></i>'.html_safe, sort_admin_variety_path('down', variety), :remote => true, :method => :put, :class => "btn", :title => "下移" %>
                </div>
            </td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/admin/varieties/edit.html.erb
<h2 class="page-header">修改菜单</h2>

<%= simple_form_for(@variety, :url => admin_variety_path(@variety) ) do |f| %>
	<%= render :partial => "form", :locals => { :f => f } %>
<% end %>

app/views/admin/varieties/index.html.erb
<%= content_for :head do %>
    <style type="text/css">
        .btn-group {
            float: right;
        }
    </style>
<% end %>

<h2 class="page-header">菜单列表</h2>
<%= render :partial => "list" %>
<br />
<%= link_to "新建模块", new_admin_variety_path,:class => "btn primary-btn" %>

app/views/admin/varieties/new.html.erb
<h2 class="page-header">新增菜单</h2>

<%= simple_form_for(@variety, :url => admin_varieties_path(@variety) ) do |f| %>
	<%= render :partial => "form", :locals => { :f => f } %>
<% end %>

app/views/admin/varieties/sort.js.erb
$('#table').html(<%=raw render(:partial => 'list').to_json %>);