config/routes.rb
Restaurant::Application.routes.draw do
  
  match '/index.asp', :to => redirect('/links.html')
  
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users
  
  namespace :admin do
    root :to => redirect {|p, r| "#{r.script_name}/admin/categories" }
    resources :categories do
      scope "/:sort" do
        put 'sort', :on => :member
      end
      resources :items
    end
    
    resources :messages do
      get 'carousel', :on => :member
    end
    
    resources :photos
    resources :cdrs
    resources :orders do
      get 'complete',  :on => :collection
      put 'onlined',   :on => :member
      put 'completed', :on => :member
    end
    
    resources :varieties do
      scope "/:sort" do
        put 'sort', :on => :member
      end
      resources :tags do
        scope "/:sort" do
          put 'sort', :on => :member
        end
      end
    end
  end
  
  resources :categories do
    get  'menu',  :on => :member
    post 'check', :on => :member
    get 'ok',    :on => :member
    post 'add', :on => :member
    get 'add_check', :on => :member
    get 'edit_check', :on => :member
    get 'cancel_check', :on => :member
    get 'list', :on => :member
  end
  
  
  root :to => redirect {|p, r| "#{r.script_name}/categories" }
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  include RankedModel
  ranks :row_order
  attr_accessible :en_name, :se_name, :code, :row_order
  has_many :items
  validates_presence_of :en_name, :se_name
end

app/controllers/admin/categories_controller.rb
#encoding: utf-8
class Admin::CategoriesController < Admin::BaseController
  def index
    @categories = Category.rank(:row_order).page(params[:page]).per(20)
  end
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])
    
    if @category.save
      flash[:notice] = "模块创建成功"
      redirect_to admin_categories_path
    else
      render :new
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      flash[:notice] = "模块修改成功"
      redirect_to admin_categories_path
    else
      render :edit
    end
  end
  
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "模块删除成功"
    redirect_to admin_categories_path
  end
  
  def sort
    categories = Category.rank(:row_order).all
    category = Category.find(params[:id])
    
    index = categories.index(category)
    index = (params[:sort] == 'up') ? ((index - 1) < 0 ? 0 : index - 1) : ((index + 1 > categories.size - 1) ? categories.size - 1 : index + 1)
    category.update_attribute :row_order_position, index
    @categories = Category.rank(:row_order).page(params[:page]).per(20)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < BaseController
  before_filter :get_left_menu_data
  
  def index
    redirect_to category_path(Category.find_by_code("home"))
  end
  
  def show
    case 
    when !params[:id] || Category.find(params[:id]).code == "home"
      @category = Category.find_by_code("home")
      @photos = Photo.all
      render :action => "home"
    when !params[:id] || Category.find(params[:id]).code == "map"
      @category = Category.find_by_code("map")
      render :action => "map"
    when Category.find(params[:id]).code == "contact"
      @category = Category.find_by_code("contact")
      @item = @category.items.first
      render :action => "contact"
    when Category.find(params[:id]).code == "menu"
      redirect_to menu_category_path(params[:id])
    else
      @category = Category.find(params[:id])
      @item = @category.items.first
    end
  end
  
  def menu
    @code = UUIDTools::UUID.random_create.to_s
    @category = Category.find(params[:id])
    @item = @category.items.first
    @varieties = Variety.roots.rank(:row_order)
    @tags = @varieties.map(&:children)
    @order = Order.new
    @checks = [Check.new]
  end
  
  def check
    @category = Category.find(params[:id])
    @code = params[:code]
    @order = Order.new(params[:order])
    @order.save
  end
  
  def ok
    relation_order_with_checks
    UserMailer.order_email("order@chowmein.se", @order).deliver
  end
  
  def add
    @code = params[:check][:code]
    @category = Category.find(params[:id])
    @check = Check.new(params[:check])
    relation_check_with_varieties
  end
  
  def add_check
    @category = Category.find(params[:id])
    @code = params[:code]
    @check = Check.new(:code => @code)
    @varieties = Variety.roots.rank(:row_order)
    @tags = @varieties.map(&:children)
  end
  
  def edit_check
    @category = Category.find(params[:id])
    @code = params[:code]
    @check = Check.find(params[:check_id])
    @varieties = Variety.roots
    @tags = @varieties.map(&:children)
  end
  
  def cancel_check
    @category = Category.find(params[:id])
    @code = params[:code]
    @check = Check.find(params[:check_id])
    @check.destroy
  end
  
  def list
    @category = Category.find(params[:id])
    @code = params[:code]
    @checks = Check.where(:code => @code)
    @order = Order.find(params[:order_id])
    render :layout => nil
  end
  
  private
  def get_left_menu_data
    @categories = Category.rank(:row_order)
  end
  
  def relation_check_with_varieties
    varieties_id = params[:variety].values
    varieties_id.each {|id| @check.varieties << Variety.find(id) }
    @check.save!
  end
  
  def relation_order_with_checks
    @checks = Check.where(:code => params[:code])
    @order = Order.find(params[:order_id])
    @order.checks << @checks
    @order.state = "online"
    @order.save!
  end
  
end

app/views/categories/_check_form.html.erb
<div class="check alert alert-info">
<%= simple_form_for check, :url => add_category_path(@category), :remote => true, :class => "check-form" do |f| %>
	<% @varieties.each_with_index do |variety, index| %>
		<div class="radio-toolbar">
			<div><%= show_value_with_language(variety, "name") %></div>
			<% @tags[index].rank(:row_order).each_with_index do |tag, i| %>
			<div class="radio">
				<% if @variety && value = @variety[index.to_s]  %>
					<%= radio_button("variety", index, tag.id, :checked =>  value.to_i == tag.id) %>
				<% else %>
					<%= radio_button("variety", index, tag.id, :checked => i == 0) %>
				<% end -%>
				<%= show_value_with_language(tag, "name") %>
			</div>
			<% end %>
		</div>
		<br/><br/>
	<% end %>
	<br/>
	<%= f.input :num, :collection => 1..1000, :label => (session[:local] == "en" ? "number" : "nummer"), :include_blank => false %>
	<%= hidden_field_tag "check[code]", @code.to_s %>
	<%= submit_tag "Save order", class: "btn btn-large check-submit", :disable_with => "Please wait..." %>
		
	<% if check.id %>
		<%= link_to "#", :"data-url" => cancel_check_category_path(@category, :check_id => check, :code => @code), :class => "btn btn-large edit_check" , :confirm => "are you sure?" do %>
			<i class="icon-remove-sign"></i> Cancel
		<% end %>
	<% else %>
		<%= link_to "#", :class => "btn btn-large cancel_check_without_id" , :confirm => "are you sure?" do %>
			 <i class="icon-remove-sign"></i> Cancel
		<% end %>
	<% end %>
<% end %>
</div>

app/views/categories/_menu_form.html.erb
<%= simple_form_for @order, :url => check_category_path(@category, :code => @code), :remote => true do |f| %>
	<br/>
	<div class="page-info well">Your personal information</div>
	<%= f.input :address,:label => (session[:local] == "en" ? "Address" : "Adress") %>
	<%= f.input :telephone,:label => (session[:local] == "en" ? "Telephone" : "Telefon") %>
	<%= f.input :name,:label => (session[:local] == "en" ? "Name" : "Namn") %>
	<%= f.input :email,:label => (session[:local] == "en" ? "Email" : "E-post") %>
	<style type="text/css">
		textarea {
			width: 400px;
			height: 110px;
		}
	</style>
	<%= f.input :description,:label => (session[:local] == "en" ? "Description" : "Beskrivning") %>
	<%= submit_tag "Submit", class: "btn btn-large btn-primary", :disable_with => "Please wait..." %>
<% end %>

app/views/categories/add.js.erb
<%=raw render(:partial => 'check_info', :locals => { :check => @check}).to_json %>

app/views/categories/add_check.js.erb
<%=raw render(:partial => 'check_form', :locals => { :check => @check}).to_json %>

app/views/categories/cancel_check.js.erb
<%= raw Category.last.to_json %>

app/views/categories/check.html.erb
<div id="check" class="content">
	<div class="label label-info">
		ok! your order is complete!
		<br/><br/><br/>
		the worker will call some  time later!
	</div>
</div>

app/views/categories/check.js.erb
<% if @order.valid? %>

Shadowbox.open({
	player:     'iframe',
	content: 	<%=raw list_category_path(@category, :code => @code, :order_id => @order.id).to_json %>
});

<% else %>

$(".information").html(<%=raw render(:partial => 'menu_form').to_json %>);

<% end %>

app/views/categories/edit_check.js.erb
<%=raw render(:partial => 'check_form', :locals => { :check => @check}).to_json %>

app/views/categories/home.html.erb
<%= content_for :head do %>
  <%= stylesheet_link_tag "flexslider", :media => "all" %>
  <%= javascript_include_tag "jquery.flexslider-min" %>
  <script type="text/javascript">
    $(document).ready(function() {
        $('.flexslider').flexslider({
          animation: "slide"
        });
    });
  </script>
<% end -%>
<div class="content">
  <div class="flexslider">
    <ul class="slides">
      <% @photos.each_with_index do |photo, index| %>
      <li><%= image_tag photo.poster_url(:thumb), :size => "800*500"%></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/categories/list.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
	<title>Restaurant</title>
	<meta charset="utf-8">
	<%= stylesheet_link_tag "admin", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= javascript_include_tag "ckeditor/init" %>
	<%= csrf_meta_tags %>
	<%= stylesheet_link_tag "shadowbox", :media => "all" %>
	<%= javascript_include_tag "shadowbox" %>
	<script type="text/javascript">
	    Shadowbox.init();
	</script>
	<%= yield :head %>
	<script type="text/javascript">
		$(document).ready(function() {
			$(".cancel").live("click", function() {
				window.parent.Shadowbox.close();
			});
			
			$(".ok").live("click", function() {
				$(window).bind("click", function(event) {
					event.stopPropagation();
					event.preventDefault();
				}) 
				$(".container").html("<div class='label label-info' style='height:100px;margin-top:100px;font-size:30px;line-height:100px'>please wait a moment!</div>");
				
				var p$ = window.parent.$;
				p$.bind("click", function(event) {
					event.stopPropagation();
					event.preventDefault();
				}) 
				p$(".loading").show();
				p$("a").href = "#";
				p$("a").unbind("click");
				p$("form").action = "#";
				window.parent.location.href = $(this).attr('data-url');
				// window.parent.Shadowbox.close();
			})
		})
	</script>
</head>
<body>
	<h2 class="page-header" style="padding-left: 130px">the order detail</h2>
	<div id="main-container" class="container">
		<h2> the total price: <%= (@checks.to_a.map(&:num).inject(&:+) || 0) * 60 %> sek</h2>
		<br/>
		<h2> Your Information </h2>
		<table class="table table-bordered table-striped">
			<tr>
				<th>
					name
				</th>
				<td>
					<%= @order.name %>
				</td>
			</tr>
			<tr>
				<th>
					address
				</th>
				<td>
					<%= @order.address %>
				</td>
			</tr>
			<tr>
				<th>
					telephone
				</th>
				<td>
					<%= @order.telephone %>
				</td>
			</tr>
			<tr>
				<th>
					description
				</th>
				<td>
					<%= @order.description %>
				</td>
			</tr>
		</table>
		<h2> the order list</h2>
		<% @checks.each do |check| %>
			<table class="table table-bordered table-striped">
				<tr>
					<th>
						number
					</th>
					<td>
						<%= check.num %>
					</td>
				</tr>
				<% check.varieties.each do |variety| %>
				<tr>
					<th>
						<%= session[:local] == "en" ? variety.parent.en_name : variety.parent.se_name %>:
					</th>
					<td>
						<%= session[:local] == "en" ? variety.en_name : variety.se_name %>
					</td>
				</tr>
				<% end %>
			</table>
		<% end %>
		<style type="text/css">
			.btn-primary {
				width: 100px;
			}
		</style>
		<%= link_to "OK", "#", :"data-url" => ok_category_path(@category, :code => @code, :order_id => @order.id), :class => "btn btn-large btn-primary ok" %>
		<%= link_to "Cancel", "#", :class => "btn btn-large cancel" %>
	</div>

</body>
</html>

app/views/categories/map.html.erb
<%= content_for :head do %>
  <script type="text/javascript"
    src="https://maps.google.com/maps/api/js?sensor=true">
  </script>
  <script type="text/javascript">
  //56.670448,12.87102 
    function initialize() {
      var latlng = new google.maps.LatLng(56.669953,12.871256);
      var myOptions = {
        zoom: 14,
        center: latlng,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      var map = new google.maps.Map(document.getElementById("map_canvas"),
          myOptions);
      
      var contentString = '<div id="content">'+
      '<div id="siteNotice">'+
      '</div>'+
      '<h1 id="firstHeading" class="firstHeading">Welcome to Beni\'s restaurant!</h1>'+
      '<div id="bodyContent">'+
      '<p><b>Beni\'s restaurant</b>, also referred to as <b>Ayers Rock</b>' +
      'sandstone rock formation in the southern part of the '+
      'Northern Territory, central Australia'+
      'south west of the nearest large town'+
      'rock caves and ancient paintings. Uluru is listed as a World '+
      'Heritage Site.</p>'+
      '<p>Attribution: Uluru,'+
      'http://en.wikipedia.org/w/index.php?title=Uluru</a> .</p>'+
      '</div>'+
      '</div>';

      var infowindow = new google.maps.InfoWindow({
          content: contentString
      });

      var marker = new google.maps.Marker({
          position: latlng,
          map: map,
          title: "Beni's restaurant!"
      });

      google.maps.event.addListener(marker, 'click', function() {
        infowindow.open(map,marker);
      });
    }

  </script>
  <script type="text/javascript">
    $(document).ready(function() {
      initialize();
    })
  </script>
<% end -%>
<div class="content">
  <div id="map_canvas"></div>
</div>

app/views/categories/menu.html.erb
<%= content_for :head do %>
	<script type="text/javascript">
		$(document).ready(function() {
			$(".check-submit").live("click", function(event) {
				event.preventDefault();
				var self = this;
				$(".loading").show();
				$.ajax({
					type: 'POST',
					url: $(this).closest("form").attr('action'),
					data: $(this).closest("form").serialize(),
					dataType: 'json',
					success: function(json) {
						$(".loading").hide();
						$(json).insertAfter($(self).closest(".check"));
						$(self).closest(".check").remove();
					}
				})
			})
			
			$(".add_check").live("click", function(event) {
				event.preventDefault();
				var self = this;
				$(".loading").show();
				$.ajax({
					type: 'GET',
					url: $(this).attr('data-url'),
					data: $(this).closest("form").serialize(),
					dataType: 'json',
					success: function(json) {
						$(".loading").hide();
						$(".checks").append(json);
					}
				})
			})
			
			$(".edit_check").live("click", function(event) {
				event.preventDefault();
				event.stopPropagation();
				var self = this;
				$(".loading").show();
				$.ajax({
					type: 'GET',
					url: $(this).attr('data-url'),
					data: $(this).closest("form").serialize(),
					dataType: 'json',
					success: function(json) {
						$(".loading").hide();
						$(json).insertAfter($(self).closest(".check"));
						$(self).closest(".check").remove();
					}
				})
				return false;
			})
			
			$(".cancel_check").live("click", function(event) {
				event.preventDefault();
				var self = this;
				$(".loading").show();
				$.ajax({
					type: 'GET',
					url: $(this).attr('data-url'),
					data: $(this).closest("form").serialize(),
					dataType: 'json',
					success: function(json) {
						$(".loading").hide();
						$(self).closest(".check").remove();
					}
				})
				return false;
			})
			
			$(".cancel_check_without_id").live("click", function(event) {
				event.preventDefault();
				$(this).closest(".check").remove();
			})


		})

		window.onscroll = function() {
			$(".loading")[0].style.top = (document.documentElement.scrollTop + (document.documentElement.clientHeight - $(".loading")[0].offsetHeight) / 2) + "px";
			$(".loading")[0].style.left = (document.documentElement.scrollLeft + (document.documentElement.clientWidth - $(".loading")[0].offsetWidth) / 2) + "px";
		}
		
	</script>
<% end %>
<div id="menu" class="content">
	<div class="introduction">
		<%=raw show_value_with_language(@item, "content") %>
	</div>
	<div class="order">
		<div class="checks">
			<div class="page-info well">Your order</div>
			<% @checks.each do |check, index| %>
			<%= render :partial => "check_form", :locals => {:check => check, :check_index => index} %>
			<% end %>
		</div>
		<br/>
		<%= link_to "#", :"data-url" => add_check_category_path(@category, :code => @code), :class => "btn btn-large add_check" do %>
			<i class="icon-plus-sign"></i> Add order
		<% end %>
		<div class="information">
			<%= render :partial => "menu_form" %>
		</div>
	</div>
</div>

app/views/categories/ok.html.erb
<div id="check" class="content">
	<div class="label label-info">
		Ok! Your order is complete!
		<br/><br/>
		Your order is No.<%= Order.online.size - 1 %> in the queue.
		<br/><br/>
		Our staff will contact with you to confirm the order as soon as possible.
		<br/><br/>
		If there is no reply within 10 minutes. You can try to call us yourself. 
		<br/><br/>
		Our home delivery service is available from:
		<br/><br/>
		Monday ~ Thursday & Sunday 12:00-21:00
		<br/><br/>
		Friday & Saturday 15:00-24:00
	</div>
</div>

app/views/categories/show.html.erb
<div class="content">
	<%=raw show_value_with_language(@item, "content") %>
</div>