config/routes.rb
Restaurant::Application.routes.draw do
  
  match '/index.asp', :to => redirect('/links.html')
  
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users
  
  namespace :admin do
    root :to => redirect {|p, r| "#{r.script_name}/admin/categories" }
    resources :categories do
      scope "/:sort" do
        put 'sort', :on => :member
      end
      resources :items
    end
    
    resources :messages do
      get 'carousel', :on => :member
    end
    
    resources :photos
    resources :cdrs
    resources :orders do
      get 'complete',  :on => :collection
      put 'onlined',   :on => :member
      put 'completed', :on => :member
    end
    
    resources :varieties do
      scope "/:sort" do
        put 'sort', :on => :member
      end
      resources :tags do
        scope "/:sort" do
          put 'sort', :on => :member
        end
      end
    end
  end
  
  resources :categories do
    get  'menu',  :on => :member
    post 'check', :on => :member
    get 'ok',    :on => :member
    post 'add', :on => :member
    get 'add_check', :on => :member
    get 'edit_check', :on => :member
    get 'cancel_check', :on => :member
    get 'list', :on => :member
  end
  
  
  root :to => redirect {|p, r| "#{r.script_name}/categories" }
  
end

app/views/layouts/admin.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
	<title>Restaurant</title>
	<meta charset="utf-8">
	<%= stylesheet_link_tag "admin", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= javascript_include_tag "ckeditor/init" %>
	<%= csrf_meta_tags %>
	<%= stylesheet_link_tag "shadowbox", :media => "all" %>
	<%= javascript_include_tag "shadowbox" %>
	<script type="text/javascript">
	    Shadowbox.init();
	</script>
	<%= yield :head %>
</head>
<body>

<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="#">Restaurant</a>

			<% if user_signed_in? %>
			<ul class="nav">
				<li>
					<%= link_to "页面管理", admin_messages_path %>
				</li>
				<li>
					<%= link_to "模块管理", admin_categories_path %>
				</li>
				<li>
					<%= link_to "菜单管理", admin_varieties_path %>
				</li>
				<li>
					<%= link_to "图片管理", admin_photos_path %>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"> 订单管理<b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><%= link_to "未送餐列表", admin_orders_path %></li>
						<li><%= link_to "已送餐列表", complete_admin_orders_path %></li>
					</ul>
				</li>
				<li>
					<%= link_to "访问管理", admin_cdrs_path %>
				</li>
			</ul>

			<ul class="nav pull-right">
				<li class=""><a href="#"><%= current_user.email %></a></li> 
				<li class=""><%= link_to '注销', destroy_user_session_path, :method => 'delete' %></li>
			</ul>
			<% end %>

		</div>
	</div>
</div>

<% if content_for?(:sidebar) %>
	<div id="main-container" class="container-fluid">
		<div class="row-fluid">
			<div class="span2 sidebar">
				<%= yield(:sidebar) %>
			</div>
			<div class="span10">
				<% flash.each do |name, message| %>
				<div class="alert alert-<%= name %> fade in">
					<button class="close" data-dismiss="alert">×</button>
					<%= message %>
				</div>
				<% end %>
				
				<%= yield %>
			</div>
		</div>
	</div>
<% else %>
	<div id="main-container" class="container">
		<% flash.each do |name, message| %>
		<div class="alert alert-<%= name %>">
			<button class="close" data-dismiss="alert">×</button>
			<%= message %>
		</div>
		<% end %>
		<%= yield %>
	</div>
<% end %>

<footer></footer>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--[if lt IE 7 ]> <html dir="ltr" lang="en-US" class=" ie6"> <![endif]-->
<!--[if IE 7 ]>    <html dir="ltr" lang="en-US" class="ie7"> <![endif]-->
<!--[if (gt IE 7)|!(IE)]><!--> <html dir="ltr" lang="en-US"> <!--<![endif]-->

<head profile="http://gmpg.org/xfn/11">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title> Äkta Kinesisk Kock </title>
    <meta name="viewport" content="width=device-width, user-scalable=yes initial-scale=1.0, minimum-scale=1.0">
	<link href='http://fonts.googleapis.com/css?family=Lobster&subset=latin' rel='stylesheet' type='text/css'>
	<%= stylesheet_link_tag    "menu", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<%= stylesheet_link_tag "shadowbox", :media => "all" %>
	<%= javascript_include_tag "shadowbox" %>
	<script type="text/javascript">
	    Shadowbox.init();
	</script>
	<%= yield :head %>
</head>

<body class="home blog" >

<div id="canvas">
	<div id="social-icons">
		<a href="http://www.facebook.com/pages/ChowMein/399045123525043" class="facebook">Facebook</a>
		<div id="dropdown" class="dropdown">
			<button class="btn btn-inverse dropdown-toggle" data-toggle="dropdown">
				<%= session[:local] == "en" ? "English" : "svenska" %>
				<span class="caret"></span>
			</button>
			<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
				<li><%= link_to "English", categories_path(:local => "en"), :tabindex => "-1" %></li>
				<li class="divider"></li>
				<li><%= link_to "svenska", categories_path(:local => "se"), :tabindex => "-1" %></li>
			</ul>
		</div>
	</div>
	<ul class="skip">
		<li><a href=".menu">Skip to navigation</a></li>
		<li><a href="#primaryContent">Skip to main content</a></li>
		<li><a href="#secondaryContent">Skip to secondary content</a></li>
		<li><a href="#footer">Skip to footer</a></li>
	</ul>

	<div id="header-wrap">
		<div id="header"> 
			<h1 id="site-title">
				<span>
					<a href="#" title="restaurant" rel="home">Äkta Kinesisk Kock</a>
				</span>
			</h1>
			
      <!--by default your pages will be displayed unless you specify your own menu content under Menu through the admin panel-->
		</div> <!-- end #header-->
	</div> <!-- end #header-wrap-->
	<div id="secondaryContent">
		<ul>
			<li id="linkcat-2" class="linkcat">Navigation
				<ul class='xoxo blogroll'>
					<% @categories.each do |category| %>
					<li>
						<%= link_to show_value_with_language(category, "name"), category_path(category) %>
					</li>
					<% end %>
				</ul>
			</li>
		</ul>
	</div>
	<div id="primaryContent">
		<%= yield %>
	</div>
</div>
<div id="footer">
	<p>Copyright &copy; 2013 | Äkta Kinesisk Kock | Föreningsgatan 1 | 302 49 Halmstad | Tel :+46 736267385 | order@chowmein.se</p>
</div>
</div>
<div id="loading" class="loading" style="display:none"></div>
</body>
</html>